# Generated by Django 4.0.3 on 2022-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_userresponse_options_userresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='points_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
