# Generated by Django 4.0.3 on 2022-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
